# Generated by Django 4.1.5 on 2023-05-12 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='difficulty',
        ),
    ]
